# auto-generated by perf_report.py -- official grading contract replica
import importlib.util, json, os, sys, time, traceback

def main():
    prob_path, tl, alg_dir, out_path = sys.argv[1], float(sys.argv[2]), sys.argv[3], sys.argv[4]
    t_proc0 = time.perf_counter()
    sys.path.insert(0, alg_dir)
    spec = importlib.util.spec_from_file_location("myalgorithm", os.path.join(alg_dir, "myalgorithm.py"))
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    with open(prob_path, "r", encoding="utf-8") as f:
        prob = json.load(f)
    t_import = time.perf_counter() - t_proc0

    res = {"ok": False, "t_import_s": round(t_import, 3), "t_algo_s": None,
           "solution": None, "traceback": None}
    t0 = time.perf_counter()
    try:
        sol = mod.algorithm(prob, tl)
        res["ok"] = True
        res["solution"] = sol
    except Exception:
        res["traceback"] = traceback.format_exc()
    res["t_algo_s"] = round(time.perf_counter() - t0, 3)

    tmp = out_path + ".tmp"
    with open(tmp, "w", encoding="utf-8") as f:
        json.dump(res, f)
    os.replace(tmp, out_path)

main()
